version: '3.7'

services:

  db:
    image: postgres
    container_name: database_service
    environment:
      POSTGRES_DB: models_db
      POSTGRES_USERNAME: mypostgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    expose:
      - 5432

  wineestimator:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    container_name: api_service
    ports:
      - "5000:5000"
  
